In [ ]:
import numpy as np

In [ ]:
x = np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y = np.array([[1],[1],[0]])

# 1,0,1,0 --> 1
# 1,0,1,1 --> 1
# 0,1,0,1 --> 0
# x --> features, y--> target

In [ ]:
x.shape

(3, 4)

In [ ]:
#setting number of neurons
inputNeurons = x.shape[1]
hiddenNeurons = 4
outputNeurons = 1
alpha = 0.01

In [ ]:
#initializing weights for hidden layer
weightsHidden = np.random.uniform(size = (inputNeurons, hiddenNeurons)) # 4 x 4
biasHidden = np.random.uniform(size = (1, hiddenNeurons)) # 1 x 4

weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons)) # 4 x 1
biasOutput = np.random.uniform(size = (1,outputNeurons)) # 1 x 1

In [ ]:
biasHidden

array([[0.79350932, 0.67489633, 0.72925127, 0.85895178]])

In [ ]:
def sigmoid(x):
  return 1/(1+ np.exp(-x))

def derivativeSigmoid(x):
  return x*(1-x)

In [ ]:
#Feedforward

#Step 1: apply linear equation
fx1 = np.dot(x, weightsHidden) + biasHidden

#Step 2: apply activation for non-linearity
z = sigmoid(fx1)

#Step 3: apply linear equation on output of hidden layer
fx2 = np.dot(z, weightsOutput) + biasOutput

#Step 4: apply activation on output layer
output = sigmoid(fx2)


In [ ]:
fx1

array([[1.61953089, 1.63122359, 2.20395245, 2.53151668],
       [2.15662053, 2.2517624 , 2.93375381, 2.81140119],
       [2.08999998, 1.95340202, 2.09037843, 1.58536942]])

In [ ]:
z

array([[0.83473042, 0.83633719, 0.90060388, 0.92632193],
       [0.89628582, 0.90480245, 0.94949001, 0.94328882],
       [0.88992742, 0.87581712, 0.88996449, 0.82996362]])

In [ ]:
output

array([[0.92433157],
       [0.93244848],
       [0.92269793]])

In [ ]:
y

array([[1],
       [1],
       [0]])

In [ ]:
outputLoss = output - y
outputLoss

array([[-0.07566843],
       [-0.06755152],
       [ 0.92269793]])

In [ ]:
outputSlope = derivativeSigmoid(output)

In [ ]:
output

array([[0.92433157],
       [0.93244848],
       [0.92269793]])

In [ ]:
outputSlope

array([[0.06994272],
       [0.06298831],
       [0.07132646]])

In [ ]:
outputDelta = outputLoss * outputSlope

In [ ]:
outputDelta

array([[-0.00529246],
       [-0.00425496],
       [ 0.06581277]])

In [ ]:
hiddenLoss = np.dot(outputDelta, weightsOutput.T)
#shape of outputdelta = 3,1
#shape of weightsoutput = 4,1
#so we will transpose weightsOutput

In [ ]:
hiddenLoss

array([[-0.00225555, -0.00511525, -0.00167437, -0.00447332],
       [-0.00181338, -0.00411249, -0.00134613, -0.0035964 ],
       [ 0.02804818,  0.06360917,  0.02082109,  0.05562671]])

In [ ]:
hiddenSlope = derivativeSigmoid(z)
hiddenDelta = hiddenLoss * hiddenSlope

In [ ]:
#first part of back propagation i.e loss is now done

In [ ]:
#now comes weights and bias updation

In [ ]:
weightsOutput = weightsOutput - z.T.dot(outputDelta) * alpha
weightsHidden = weightsHidden - hiddenDelta.T.dot(x) * alpha

In [ ]:
biasOutput = biasOutput - np.sum(outputDelta) * alpha
biasHidden = biasHidden - np.sum(hiddenDelta) * alpha

In [ ]:
epochs = 100
weightsHidden = np.random.uniform(size = (inputNeurons, hiddenNeurons)) # 4 x 4
biasHidden = np.random.uniform(size = (1, hiddenNeurons)) # 1 x 4
weightsOutput = np.random.uniform(size=(hiddenNeurons, outputNeurons)) # 4 x 1
biasOutput = np.random.uniform(size = (1,outputNeurons)) # 1 x 1

for i in range(epochs):
  #Feed Forward
  #Step 1: apply linear equation
  fx1 = np.dot(x, weightsHidden) + biasHidden

  #Step 2: apply activation for non-linearity
  z = sigmoid(fx1)

  #Step 3: apply linear equation on output of hidden layer
  fx2 = np.dot(z, weightsOutput) + biasOutput

  #Step 4: apply activation on output layer
  output = sigmoid(fx2)


  #Back propagation
  outputLoss = output - y
  outputSlope = derivativeSigmoid(output)
  outputDelta = outputLoss * outputSlope

  hiddenLoss = np.dot(outputDelta, weightsOutput.T)
  hiddenSlope = derivativeSigmoid(z)
  hiddenDelta = hiddenLoss * hiddenSlope

  #weights and bias optimization
  weightsOutput = weightsOutput - z.T.dot(outputDelta) * alpha
  weightsHidden = weightsHidden - hiddenDelta.T.dot(x) * alpha
  biasOutput = biasOutput - np.sum(outputDelta) * alpha
  biasHidden = biasHidden - np.sum(hiddenDelta) * alpha

In [ ]:
output

array([[0.82152398],
       [0.82561331],
       [0.7980992 ]])

In [ ]:
outputLoss

array([[-0.17847602],
       [-0.17438669],
       [ 0.7980992 ]])